busbook/booking/urls.py
# from django.conf.urls import url
from .views import *
from django.urls import path,include
from .views import *


app_name='booking'

urlpatterns=[
    path('', HomeView.as_view(), name='home'),
    path('results', ResultView.as_view(), name='result'),
    path('route/<int:id>', RouteDetail.as_view(), name='route'),
    path('your-bookings', BookingList.as_view(), name='bookinglist'),

]

busbook/busbook/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bususer.urls')),
    path('booking/',include('booking.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

busbook/booking/models.py
from django.db import models
from bususer.models import User
from datetime import datetime


class BusCompany(models.Model):
    name= models.CharField(max_length=100)
    phone=models.CharField(max_length=15)

    def __str__(self):
        return self.name

class Bus(models.Model):
    bus_no= models.CharField(max_length=50)
    company=models.ForeignKey(BusCompany, on_delete=models.CASCADE)
    totalseat=models.IntegerField(default=0)
    ac= models.BooleanField(default=False)
    driver= models.CharField(max_length=100)
    phone=models.CharField(max_length=15)
    photo=models.ImageField(upload_to='buspic')
    
    def __str__(self):
        return self.bus_no



class Route(models.Model):
    bus=models.ForeignKey(Bus, on_delete=models.CASCADE)
    source=models.CharField(max_length=100)
    destination=models.CharField(max_length=100)
    date=models.DateField()
    time= models.CharField(max_length=5)
    fare=models.IntegerField(null=False)

    def __str__(self):
        return ((self.source).capitalize() + ' to ' + (self.destination).capitalize())

    @property
    def available_seats(self):
        seats=Reservation.objects.filter(route=self, cancelled=False).values_list('seat')
        av_seats= Seat.objects.exclude(seat_id__in=seats)
        return av_seats

    @property
    def available_seats_no(self):
        seats=Reservation.objects.filter(route=self, cancelled=False).values_list('seat')
        av_seats= Seat.objects.exclude(seat_id__in=seats).count()
        return av_seats


class Seat(models.Model):
    seat_id=models.CharField(max_length=10, primary_key=True)

    def __str__(self):
        return self.seat_id


class Reservation(models.Model):
    route=models.ForeignKey(Route, on_delete=models.CASCADE)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    seat=models.ForeignKey(Seat, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=datetime.now, blank=True)
    cancelled=models.BooleanField(default=False)
    user_phone=models.CharField(max_length=15, null=True)

    def __str__(self):
        return str(self.id)

busbook/booking/views.py
from django.shortcuts import render
from .models import Route,Seat, Reservation
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
# Create your views here.
from django.views.generic import TemplateView, View, ListView
from django.core.mail import send_mail

class HomeView(TemplateView):
    template_name='booking/index.html'


class ResultView(TemplateView):
    template_name='booking/results.html'

    def get(self,request):
        source=request.GET['source'].lower()
        destination=request.GET['destination'].lower()
        date=request.GET['date']

        route= Route.objects.filter(source=source, destination=destination, date=date)
        
        return render(request, self.template_name, {'route':route})


class RouteDetail(TemplateView):
    template_name='booking/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        routeid= self.kwargs['id']
        route=Route.objects.get(id=routeid)
        context.update({'route':route})
        return context

    @method_decorator(login_required)
    def post(self,*args,**kwargs):
        routeid= self.kwargs['id']
        route=Route.objects.get(id=routeid)
        user=self.request.user
        seatid=self.request.POST.get('seat_id')
        phone=self.request.POST.get('phone')

        seat=Seat.objects.get(seat_id=seatid)
        Reservation.objects.create(user=user, seat=seat, route=route, user_phone=phone)
        # message=('Hello, Dear '+user.first_name + ' ' + user.last_name +' your bus for '+ str(route) +' on '+ str(route.date) + ',' + str(route.time) +' has been booked. Thank you.' )
        # send_mail('BusBook Nepal - Booked Success',message,'herohiralaal14@gmail.com',[user.email],fail_silently=False)
        # messages.success(self.request,'Your bus booked sucessfully! Check your bookings for detail.')
        return HttpResponseRedirect(self.request.path_info)



class BookingList(ListView):
    template_name='booking/your_bookings.html'
    context_object_name = 'booking'
    

    def get_queryset(self):
        user=self.request.user
        queryset = Reservation.objects.filter(user=user).order_by('-id')
        
        return queryset

    def post(self,*args,**kwargs):
        user=self.request.user
        reservationid= self.request.POST.get('reservation')
        reservation=Reservation.objects.get(id=reservationid)
        reservation.cancelled=True
        reservation.save()
        # message=('Hello, Dear '+user.first_name + ' ' + user.last_name +' your bus for '+ str(reservation.route) +' on '+ str(reservation.route.date) + ',' + str(reservation.route.time) +' has been cancelled. Thank you.' )
        # send_mail('BusBook Nepal - Book Cancelled!',message,'herohiralaal14@gmail.com',[user.email],fail_silently=False)
        # messages.success(self.request,'Your cancel request has sucessfully completed.')
    
        return HttpResponseRedirect(self.request.path_info)

busbook/templates/booking/index.html
{% extends 'base.html' %}

{% block title%}BusBook Home{% endblock%}

{% block navblock %}

<div class="container mt-3">
    <div class="row">
        <div class="col-lg-8">
            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img src="https://images.unsplash.com/photo-1534238754819-d8e4470ce7cc?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8YnVzZXN8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="https://images.unsplash.com/photo-1534238754819-d8e4470ce7cc?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8YnVzZXN8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" class="d-block w-100" alt="...">

                  </div>
                  <div class="carousel-item">
                    <img src="https://images.unsplash.com/photo-1534238754819-d8e4470ce7cc?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8YnVzZXN8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" class="d-block w-100" alt="...">

                  </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
        </div>
        <div class="col-lg-4">
            <div class="border p-3">
                <h4 class="fw-light text-left text-primary p-3">Start your booking</h4><hr>
                <form method="GET" action="/booking/results">
                    <div class="mb-3">
                      <label for="exampleInputEmail1" class="form-label">From:</label>
                      <input type="text" required class="form-control" name="source" id="exampleInputEmail1" aria-describedby="emailHelp">
                      <div id="emailHelp" class="form-text">Enter the location where your journey begins. </div>
                    </div>
                    <div class="mb-3">
                      <label for="exampleInputPassword1" class="form-label">To:</label>
                      <input type="text"  required class="form-control" name="destination" id="exampleInputPassword1">
                      <div id="emailHelp"  class="form-text">Enter the location you want to go. </div>

                    </div>
                    <div class="mb-3">
                    <label class="form-check-label" for="exampleCheck1">pick the date</label>
                      <input type="date" required class="form-control" name="date" id="exampleCheck1">
                      
                    </div>
                    <button type="submit" class="btn btn-primary">Search Buses</button>
                  </form>
            </div>
        </div>
    </div>
</div>



{% endblock %}

busbook/templates/booking/results.html
{% extends 'base.html' %}

{% block title%}BusBook Results{% endblock%}

{% block navblock %}


<style>
    body{
    background:#eee;    
}
.main-box.no-header {
    padding-top: 20px;
}
.main-box {
    background: #FFFFFF;
    -webkit-box-shadow: 1px 1px 2px 0 #CCCCCC;
    -moz-box-shadow: 1px 1px 2px 0 #CCCCCC;
    -o-box-shadow: 1px 1px 2px 0 #CCCCCC;
    -ms-box-shadow: 1px 1px 2px 0 #CCCCCC;
    box-shadow: 1px 1px 2px 0 #CCCCCC;
    margin-bottom: 16px;
    -webikt-border-radius: 3px;
    -moz-border-radius: 3px;
    border-radius: 3px;
}
.table a.table-link.danger {
    color: #e74c3c;
}
.label {
    border-radius: 3px;
    font-size: 0.875em;
    font-weight: 600;
}
.user-list tbody td .user-subhead {
    font-size: 0.875em;
    font-style: italic;
}
.user-list tbody td .user-link {
    display: block;
    font-size: 1.25em;
    padding-top: 3px;
    margin-left: 60px;
}
a {
    color: #3498db;
    outline: none!important;
}
.user-list tbody td>img {
    position: relative;
    max-width: 50px;
    float: left;
    margin-right: 15px;
}

.table thead tr th {
    text-transform: uppercase;
    font-size: 0.875em;
}
.table thead tr th {
    border-bottom: 2px solid #e7ebee;
}
.table tbody tr td:first-child {
    font-size: 1.125em;
    font-weight: 300;
}
.table tbody tr td {
    font-size: 0.875em;
    vertical-align: middle;
    border-top: 1px solid #e7ebee;
    padding: 12px 8px;
}
a:hover{
text-decoration:none;
}
</style>
<div class="container mt-3">
    <div class="p-3 my-2 bg-white">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <h3 class="fw-light">Best Matching Results:</h3>
            </div>
            <div class="col-lg-3 mx-auto">
                <a class="btn btn-primary" href="/booking">Manipulate search</a>
            </div>
        </div>

    </div>

    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
    <hr>
    <div class=" bootstrap snippets bootdey">
        <div class="row">
            <div class="col-lg-12">
                <div class="main-box no-header clearfix">
                    <div class="main-box-body clearfix">
                        <div class="table-responsive">
                            <table class="table user-list container">
                               
                               
                            
                                <thead>
                                    <tr>
                                    <th><span>Bus No.</span></th>
                          

                                    <th><span>Ac/Non-Ac</span></th>
                                    <th class="text-center"><span>Dep. Time</span></th>
                                    <th><span>Date</span></th>
                                    <th><span>Available seats</span></th>


                                    <th><span>Fare</span></th>

                                    <th>&nbsp;</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for i in route %}

                                    <tr>
                                        <td>
                                            <img src="{{i.bus.photo.url}}" alt="pic">
                                            <a href="{% url 'booking:route' i.id %}" class="text-decoration-none">{{i.bus.bus_no}}</a>
                                            <span class="user-subhead">{{i.bus.company.name}}</span>
                                        </td>
                                        {% if i.bus.ac == True %}
                                        <td>Ac</td>
                                        {% else %}
                                        <td>Non Ac</td>
                                        {% endif %}
                                        <td class="text-center">
                                            <span class="label label-default">{{i.time}}</span>
                                        </td>
                                        <td>
                                            <span class="label label-default">{{i.date}}</span>
                                            
                                        </td>
                                        <td>
                                            <span class="label label-default text-center mx-auto">{{i.available_seats_no}}/{{i.bus.totalseat}}</span>
                                            
                                        </td>
                                        <td>
                                            <span class="label label-default">Rs. {{i.fare}}</span>
                                            
                                        </td>
                                        <!-- <td style="width: 20%;">
                                            <a href="#" class="table-link text-warning">
                                                <span class="fa-stack">
                                                    <i class="fa fa-square fa-stack-2x"></i>
                                                    <i class="fa fa-search-plus fa-stack-1x fa-inverse"></i>
                                                </span>
                                            </a>
                                            <a href="#" class="table-link text-info">
                                                <span class="fa-stack">
                                                    <i class="fa fa-square fa-stack-2x"></i>
                                                    <i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
                                                </span>
                                            </a>
                                            <a href="#" class="table-link danger">
                                                <span class="fa-stack">
                                                    <i class="fa fa-square fa-stack-2x"></i>
                                                    <i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
                                                </span>
                                            </a>
                                        </td> -->
                                    </tr>
                                    {% empty %}
                                    <h3 class="text-center p-3">No bus found sorry!</h3>
                                    {% endfor %}
                                            
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



</div>




{% endblock %}

busbook/templates/booking/your_bookings.html
{% extends 'base.html' %}

{% block title%}BusBook Your Bookings{% endblock%}

{% block navblock %}

<style>



/* USER LIST TABLE */
.user-list tbody td > img {
    position: relative;
	max-width: 50px;
	float: left;
	margin-right: 15px;
}
.user-list tbody td .user-link {
	display: block;
	font-size: 1.25em;
	padding-top: 3px;
	margin-left: 60px;
}
.user-list tbody td .user-subhead {
	font-size: 0.875em;
	font-style: italic;
}

/* TABLES */
.table {
    border-collapse: separate;
}
.table-hover > tbody > tr:hover > td,
.table-hover > tbody > tr:hover > th {
	background-color: #eee;
}
.table thead > tr > th {
	border-bottom: 1px solid #C2C2C2;
	padding-bottom: 0;
}
.table tbody > tr > td {
	font-size: 0.875em;
	background: #f5f5f5;
	border-top: 10px solid #fff;
	vertical-align: middle;
	padding: 12px 8px;
}
.table tbody > tr > td:first-child,
.table thead > tr > th:first-child {
	padding-left: 20px;
}
.table thead > tr > th span {
	border-bottom: 2px solid #C2C2C2;
	display: inline-block;
	padding: 0 5px;
	padding-bottom: 5px;
	font-weight: normal;
}
.table thead > tr > th > a span {
	color: #344644;
}
.table thead > tr > th > a span:after {
	content: "\f0dc";
	font-family: FontAwesome;
	font-style: normal;
	font-weight: normal;
	text-decoration: inherit;
	margin-left: 5px;
	font-size: 0.75em;
}
.table thead > tr > th > a.asc span:after {
	content: "\f0dd";
}
.table thead > tr > th > a.desc span:after {
	content: "\f0de";
}
.table thead > tr > th > a:hover span {
	text-decoration: none;
	color: #2bb6a3;
	border-color: #2bb6a3;
}
.table.table-hover tbody > tr > td {
	-webkit-transition: background-color 0.15s ease-in-out 0s;
	transition: background-color 0.15s ease-in-out 0s;
}
.table tbody tr td .call-type {
	display: block;
	font-size: 0.75em;
	text-align: center;
}
.table tbody tr td .first-line {
	line-height: 1.5;
	font-weight: 400;
	font-size: 1.125em;
}
.table tbody tr td .first-line span {
	font-size: 0.875em;
	color: #969696;
	font-weight: 300;
}
.table tbody tr td .second-line {
	font-size: 0.875em;
	line-height: 1.2;
}
.table a.table-link {
	margin: 0 5px;
	font-size: 1.125em;
}
.table a.table-link:hover {
	text-decoration: none;
	color: #2aa493;
}
.table a.table-link.danger {
	color: #fe635f;
}
.table a.table-link.danger:hover {
	color: #dd504c;
}

.table-products tbody > tr > td {
	background: none;
	border: none;
	border-bottom: 1px solid #ebebeb;
	-webkit-transition: background-color 0.15s ease-in-out 0s;
	transition: background-color 0.15s ease-in-out 0s;
	position: relative;
}
.table-products tbody > tr:hover > td {
	text-decoration: none;
	background-color: #f6f6f6;
}
.table-products .name {
	display: block;
	font-weight: 600;
	padding-bottom: 7px;
}
.table-products .price {
	display: block;
	text-decoration: none;
	width: 50%;
	float: left;
	font-size: 0.875em;
}
.table-products .price > i {
	color: #8dc859;
}
.table-products .warranty {
	display: block;
	text-decoration: none;
	width: 50%;
	float: left;
	font-size: 0.875em;
}
.table-products .warranty > i {
	color: #f1c40f;
}
.table tbody > tr.table-line-fb > td {
	background-color: #9daccb;
	color: #262525;
}
.table tbody > tr.table-line-twitter > td {
	background-color: #9fccff;
	color: #262525;
}
.table tbody > tr.table-line-plus > td {
	background-color: #eea59c;
	color: #262525;
}
.table-stats .status-social-icon {
	font-size: 1.9em;
	vertical-align: bottom;
}
.table-stats .table-line-fb .status-social-icon {
	color: #556484;
}
.table-stats .table-line-twitter .status-social-icon {
	color: #5885b8;
}
.table-stats .table-line-plus .status-social-icon {
	color: #a75d54;
}
</style>



<div class="container mt-3">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <h3 class="my-3 shadow p-3">Your bookings</h3>
    {% for message in messages %}
{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}

<div class="col-lg-6 mx-auto">
   
    <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
        <strong></strong>{{message}} 
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
   

</div>



            
{% endif %}

{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}

<div class="col-lg-6 mx-auto">
        <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
            <strong></strong> {{message}} 
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
    </div>




{% endif %}
{% endfor %}

<div class="row">
	<div class="col-lg-12">
		<div class="main-box clearfix">
			<div class="table-responsive">
				<table class="table user-list">
					<thead>
						<tr>
							<th><span>Bus</span></th>
							<th><span>Route</span></th>
							<th class="text-center"><span>Dep. Time</span></th>
							<th><span>Dep. Date</span></th>
							<th><span>Booked Time</span></th>
							<th><span>Seat</span></th>
                            <th><span>Status</span></th>



							<th>&nbsp;</th>
						</tr>
					</thead>
					<tbody>
                        {% for i in booking%}
						<tr>
							<td>
								<img src="{{i.route.bus.photo.url}}" alt="">
								<a href="#" class="user-link">{{i.route.bus}}</a>
								<span class="user-subhead">{{i.route.bus.company.name}}</span>
							</td>
							<td>
								{{i.route}}
							</td>
							<td class="text-center">
								<span class="label label-default">{{i.route.time}}</span>
							</td>
							<td>
								<span class="label label-default">{{i.route.date}}</span>
							</td>
                            <td>
								<span class="label label-default">{{i.date_created}}</span>
							</td>
                            <td>
								<span class="label label-default">{{i.seat}}</span>
							</td>
                            {% if i.cancelled%}
                            <td>
								<span class="label label-default">Cancelled</span>
							</td>
                            {%else%}
                            <td>
								<span class="label label-default">Going</span>
							</td>
                            {%endif%}
							<td style="width: 20%;">
                                <form method="POST">
                                    {%csrf_token%}
								<a href="{% url 'booking:route' i.route.id %}" class="table-link text-decoration-none">
                                    <i>View</i>
									<span class="fa-stack">
										<i class="fa fa-square fa-stack-2x"></i>
										<i class="fa fa-search-plus fa-stack-1x fa-inverse"></i>
									</span>
								</a>

                                    <input type="text" name="reservation" hidden value="{{i.id}}">
								
                                    {% if i.cancelled%}
                                    <button   class="btn btn-outline-danger btn-sm disabled">
										<i class="fa fa-times-circle "></i>
                                    <i>Cancel</i>
								    </button>
                                    {%else%}
                                    <button  type="submit" onclick="return confirm('Are you sure want to cancel the trip?')" class="btn btn-outline-danger btn-sm">
										<i class="fa fa-times-circle "></i>
                                    <i>Cancel</i>
								    </button>
                                    {%endif%}
                                

                                </form>
                               
							</td>
						</tr>
                        {%empty%}
                        <h3 class="text-center my-3">No bookings yet.</h3>
                        {% endfor %}
						
					</tbody>
				</table>
			</div>
		
		</div>
	</div>
</div>


</div>



{%endblock%}