busbook/booking/urls.py
# from django.conf.urls import url
from .views import *
from django.urls import path,include
from .views import *


app_name='booking'

urlpatterns=[
    path('', HomeView.as_view(), name='home'),
    path('results', ResultView.as_view(), name='result'),
    path('route/<int:id>', RouteDetail.as_view(), name='route'),
    path('your-bookings', BookingList.as_view(), name='bookinglist'),

]

busbook/busbook/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bususer.urls')),
    path('booking/',include('booking.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

busbook/bususer/urls.py
# from django.conf.urls import patterns, url
from .views import *
from django.urls import path,include
from .views import UserSignin, UserLogin,ActivateAccount
from django.contrib.auth.views import LogoutView

app_name='bususer'

urlpatterns=[
    path('signup/', UserSignin.as_view(), name='signup'),
    path('', UserLogin.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('activate/<str:uidb64>/<str:token>',ActivateAccount.as_view(),name='activate'),
    path('sent/', activation_sent_view, name='sent'),
    path('invalid',activation_invalid_view, name='invalid'),

  



  
]

busbook/bususer/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser#, UserManager
from .managers import UserManager

# Create your models here.
class User(AbstractUser):
    username = None#models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    # first_name = models.CharField(max_length=255)
    # last_name = models.CharField(max_length=255)
    email_confirmed = models.BooleanField(default=False) #initially this field is false but will se chan
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False) # a admin user; non super-user
    is_admin = models.BooleanField(default=False)
    is_seller = models.BooleanField(default=False)
    is_customer = models.BooleanField(default=False)
 

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = [] #emaila nd password are required fields and first name and last name is inherited from the user creation model

    #instanciate the usermanager object
    object = UserManager()

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    
   

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):              # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True
    #
    # def email_user(self, subject, message, from_email=None, **kwargs):
    #     send_mail(subject, message, from_email, [self.email], **kwargs)

    #
    # @property
    # def is_staff(self):
    #     "Is the user a member of staff?"
    #     return self.is_staff
    #
    # @property
    # def is_admin(self):
    #     "Is the user a admin member?"
    #     return self.is_admin
    #
    # @property
    # def is_active(self):
    #     "Is the user active?"
    #     return self.is_active

busbook/bususer/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, ReadOnlyPasswordHashField
from .models import User

class RegisterForm(UserCreationForm):
    # password0 = forms.CharField(widget=forms.PasswordInput)
    # password1 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)
    # prepopulated_fields = {'username': ('first_name', 'last_name',)}

    class Meta():
        model = User
        fields = ('email', 'first_name', 'last_name')


    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")
        return email

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

busbook/bususer/views.py
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.hashers import make_password

from django.views.generic import View
# from .models import UserProfile
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect, HttpResponse


def userlogout(request):
    logout(request)
    return redirect('/')



from django.shortcuts import render
from django.views.generic import TemplateView, View
from .forms import RegisterForm
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.contrib import messages
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .models import User
from django.conf import settings
from django.http import HttpResponse

# from django.contrib.auth import get_user_model
# User = get_user_model()

# from accounts.tokens import account_activation_token

# Create your views here.


class UserLogin(LoginView):
    template_name = 'bususer/login.html'
    success_url = 'bususer:signup'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'login_active':'active'})
        return context
    


class UserLogoutView(LogoutView):
    success_url = reverse_lazy('accounts:home')
    template_name = 'registration/logged_out'

class UserSignin(CreateView):
    form_class = RegisterForm
    template_name = 'bususer/register.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'signup_active':'active'})
        return context

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form':form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            #set user to inactive until the email confirmation is sent
            # user = request.user
            user.is_active = False
            user.save()
            # send confirmation email
            current_site = get_current_site(request)
            subject = 'Activate your account'
            message = render_to_string('bususer/account_activate_email.html', {
                'user':user,
                'domain':current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.id)),
                'token':default_token_generator.make_token(user),
            })
            print(message)
            user.email_user(subject, message, from_email=None, **kwargs)
            messages.success(request, 'Please confirm your email to complete registration')
            return redirect('bususer:login')
        return render(request, self.template_name, {'form':form})

class ActivateAccount(View):

    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_bytes(urlsafe_base64_decode(uidb64)).decode()
            user = User.objects.get(id=uid)
            # print(uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        # User = get_user_model()
        # print(uid)
        # uid = force_text(urlsafe_base64_decode(uidb64))#.decode()
        # # uid = int(uida,10) invalid literal for int() with base 10: b'l\xc4'
        # #the value of uid is b'l\xcc' need to convert this to 1
        # user = User.objects.get(id=uid)
        # # print(uid)

        if user is not None and default_token_generator.check_token(user, token):
            # obj, created = User.objects.get_or_create(user=user)
            user.is_active = True
            user.email_confirmed = True
            user.save()
            login(request, user)
            messages.success(request,('Your account have been confirmed.'))
            return redirect('bususer:login')
        else:
            # messages.warning(request, ('The confirmation link was invalid, possibly because it has already been used.'))
            # return redirect('accounts:activation_invalid')
            return HttpResponse ('The confirmation link was invalid, possibly because it has already been used.')

def activation_sent_view(request):
    return render(request,'bususer/activation_sent.html')

def activation_invalid_view(request):
    return render(request,'bususer/activation_invalid.html')







 
    

        

busbook/templates/bususer/account_activate_email.html
{% autoescape off %}

{{ csrf_token }}

Hi {{ user.first_name }} {{user.last_name}},

Please click the link below to confirm your registration:

http://{{ domain }}{% url 'bususer:activate' uidb64=uid token=token %}

{% endautoescape %}

busbook/templates/bususer/login.html
{% extends 'base.html' %}


{% block title%}BusBook Login{% endblock%}

{% block navblock %}
<style>
    body{
  
    background: #f6f9fc;
}
.form tr{
    margin-bottom: 100px;
}
.account-block {
    padding: 0;
    background-image: url('https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=749&q=80');
    background-repeat: no-repeat;
    background-size: cover;
    height: 100%;
    position: relative;
}
.account-block .overlay {
    -webkit-box-flex: 1;
    -ms-flex: 1;
    flex: 1;
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    background-color: rgba(0, 0, 0, 0.4);
}
.account-block .account-testimonial {
    text-align: center;
    color: #fff;
    position: absolute;
    margin: 0 auto;
    padding: 0 1.75rem;
    bottom: 3rem;
    left: 0;
    right: 0;
}

.text-theme {
    color: #5369f8 !important;
}

.btn-theme {
    background-color: #5369f8;
    border-color: #5369f8;
    color: #fff;
}

label{
    display: none;
    
}
#id_username,#id_password{
    margin-bottom: 30px;
    width: 350px;
}
  





</style>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">


    <div id="main-wrapper" class="container my-5 ">
        <div class="row justify-content-center">
            <div class="col-xl-10 ">
                <div class="card border-0 shadow-sm">
                    <div class="card-body p-0">
                        <div class="row no-gutters">
                            <div class="col-lg-6">
                                <div class="p-5">
                                    {% for message in messages %} 
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
          
            <div class="col-lg-8 mx-auto">
              <div
                class="alert alert-success alert-dismissible fade show text-center"
                role="alert"
              >
                <strong></strong>{{message}} 😀
                <button
                  type="button"
                  class="btn-close"
                  data-bs-dismiss="alert"
                  aria-label="Close"
                ></button>
              </div>
            </div>
            {% endif %} {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
          
            <div class="col-lg-8 mx-auto">
              <div
                class="alert alert-danger alert-dismissible fade show text-center"
                role="alert"
              >
                <strong></strong> {{message}} 😶
                <button
                  type="button"
                  class="btn-close"
                  data-bs-dismiss="alert"
                  aria-label="Close"
                ></button>
              </div>
            </div>
            {% endif %} 
            {% endfor %}



                                    <div class="mb-5">
                                        <h3 class="h4 font-weight-bold text-theme">Login</h3>
                                    </div>
    
                                    <h6 class="h5 mb-0">Welcome back!</h6>
                                    <p class="text-muted mt-2 mb-5">Enter your email address and password to book your trip.</p>
    
                                    <form method="POST">
                                        <table class="form col-xl-10">
                                            {% csrf_token %}
                                            {{form.as_table}}
                            
                                        </table>
                                      
                                        <button type="submit" class="btn btn-theme mt-2">Login</button>
                                    </form>
                                </div>
                            </div>
    
                            <div class="col-lg-6 d-none d-lg-inline-block">
                                <div class="account-block rounded-right">
                                    <div class="overlay rounded-right"></div>
                                    <div class="account-testimonial">
                                        <h4 class="text-white mb-4">Making your trip easy and comfortable!</h4>
                                        
                                        <p>-BusBook</p>
                                    </div>
                                </div>
                            </div>
                        </div>
    
                    </div>
                    <!-- end card-body -->
                </div>
                <!-- end card -->
    
                <p class="text-muted text-center mt-3 mb-0">Don't have an account? <a href="{% url 'bususer:signup'%}" class="text-primary ml-1">register</a></p>
    
                <!-- end row -->
    
            </div>
            <!-- end col -->
        </div>
        <!-- Row -->
    </div>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
       
        $('#id_username').attr('placeholder','Email')
        $('#id_password').attr('placeholder','Password')
  
    </script>

{% endblock %}
</body>
</html>

busbook/templates/bususer/register.html
{% extends 'base.html' %}


{% block title%}BusBook Register{% endblock%}

{% block navblock %}
<style>
    body{
  
    background: #f6f9fc;
}
.form tr{
    margin-bottom: 100px;
}
.account-block {
    padding: 0;
    background-image: url('https://images.unsplash.com/photo-1494515843206-f3117d3f51b7?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8YnVzfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60');
    background-repeat: no-repeat;
    background-size: cover;
    height: 100%;
    position: relative;
}
.account-block .overlay {
    -webkit-box-flex: 1;
    -ms-flex: 1;
    flex: 1;
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    background-color: rgba(0, 0, 0, 0.4);
}
.account-block .account-testimonial {
    text-align: center;
    color: #fff;
    position: absolute;
    margin: 0 auto;
    padding: 0 1.75rem;
    bottom: 3rem;
    left: 0;
    right: 0;
}

.text-theme {
    color: #5369f8 !important;
}

.btn-theme {
    background-color: #5369f8;
    border-color: #5369f8;
    color: #fff;
}

.helptext{
    display: none;
}
  





</style>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">


    <div id="main-wrapper" class="container my-5 ">
        <div class="row justify-content-center">
            <div class="col-xl-10 ">
                <div class="card border-0 shadow-sm">
                    <div class="card-body p-0">
                        <div class="row no-gutters">
                            <div class="col-lg-6">
                                <div class="p-5">
                                    {% for message in messages %} 
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
          
            <div class="col-lg-8 mx-auto">
              <div
                class="alert alert-success alert-dismissible fade show text-center"
                role="alert"
              >
                <strong></strong>{{message}} 😀
                <button
                  type="button"
                  class="btn-close"
                  data-bs-dismiss="alert"
                  aria-label="Close"
                ></button>
              </div>
            </div>
            {% endif %} {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
          
            <div class="col-lg-8 mx-auto">
              <div
                class="alert alert-danger alert-dismissible fade show text-center"
                role="alert"
              >
                <strong></strong> {{message}} 😶
                <button
                  type="button"
                  class="btn-close"
                  data-bs-dismiss="alert"
                  aria-label="Close"
                ></button>
              </div>
            </div>
            {% endif %} 
            {% endfor %}



                                    <div class="mb-5">
                                        <h3 class="h4 font-weight-bold text-theme">Register</h3>
                                    </div>
    
                                    <h6 class="h5 mb-0">Make your travel easy</h6>
                                    <p class="text-muted mt-2 mb-5">Fill out the form to get registered.</p>
    
                                    <form method="POST">
                                        <table class="form col-xl-10">
                                            {% csrf_token %}
                                            {{form.as_table}}
                            
                                        </table>
                                      
                                        <button type="submit" class="btn btn-theme mt-5">Sign up</button>
                                    </form>
                                </div>
                            </div>
    
                            <div class="col-lg-6 d-none d-lg-inline-block">
                                <div class="account-block rounded-right">
                                    <div class="overlay rounded-right"></div>
                                    <div class="account-testimonial">
                                        <h4 class="text-white mb-4">Making your trip easy and comfortable!</h4>
                                        
                                        <p>-BusBook</p>
                                    </div>
                                </div>
                            </div>
                        </div>
    
                    </div>
                    <!-- end card-body -->
                </div>
                <!-- end card -->
    
                <p class="text-muted text-center mt-3 mb-0">Already had an account? <a href="{% url 'bususer:login'%}" class="text-primary ml-1">Login</a></p>
    
                <!-- end row -->
    
            </div>
            <!-- end col -->
        </div>
        <!-- Row -->
    </div>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  

{% endblock %}
</body>
</html>