busbook/booking/urls.py
# from django.conf.urls import url
from .views import *
from django.urls import path,include
from .views import *


app_name='booking'

urlpatterns=[
    path('', HomeView.as_view(), name='home'),
    path('results', ResultView.as_view(), name='result'),
    path('route/<int:id>', RouteDetail.as_view(), name='route'),
    path('your-bookings', BookingList.as_view(), name='bookinglist'),

]

busbook/busbook/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bususer.urls')),
    path('booking/',include('booking.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

busbook/bususer/urls.py
# from django.conf.urls import patterns, url
from .views import *
from django.urls import path,include
from .views import UserSignin, UserLogin,ActivateAccount
from django.contrib.auth.views import LogoutView

app_name='bususer'

urlpatterns=[
    path('signup/', UserSignin.as_view(), name='signup'),
    path('', UserLogin.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('activate/<str:uidb64>/<str:token>',ActivateAccount.as_view(),name='activate'),
    path('sent/', activation_sent_view, name='sent'),
    path('invalid',activation_invalid_view, name='invalid'),

  



  
]

busbook/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
      
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" >

            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'booking:home' %}"><i class="fas fa-bus text-danger"></i> BusBook</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                  <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{% url 'booking:home' %}"><i class="fas fa-home"></i> Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Settings
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'booking:bookinglist' %}">Your bookings</a></li>
                        <li><a class="dropdown-item" onclick="return confirm('Really want to logout?')" href="{% url 'bususer:logout'%}">Logout</a></li>
                      
                      </ul>
                    </li>
                    {%else%}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'bususer:login'%}">Login</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'bususer:signup'%}">Signup</a>
                    </li>

                    {%endif%}
                   
                    
                  </ul>
                </div>
              </div>
            



          </nav>


    </div>
          


  <script src="https://kit.fontawesome.com/60f8143899.js" crossorigin="anonymous"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% block navblock %}
    {% endblock %}
  </body>
</html>